# Generated by Django 5.2.14 on 2026-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_scanreport_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('vendor_name', models.CharField(max_length=120)),
                ('match_terms', models.TextField(blank=True, help_text='Comma-separated terms used for matching (e.g. dell,latitude,optiplex)')),
                ('source_type', models.CharField(choices=[('oem', 'OEM'), ('component', 'Component'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('support_url', models.URLField(blank=True)),
                ('driver_url', models.URLField(blank=True)),
                ('troubleshooting_url', models.URLField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'vendor_name'],
            },
        ),
    ]
