# Generated by Django 5.2.14 on 2026-06-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_driversource'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversource',
            name='customer_segment',
            field=models.CharField(choices=[('general', 'General'), ('smallbiz', 'Small Business'), ('msp', 'MSP'), ('enterprise', 'Enterprise'), ('gaming', 'Gaming'), ('creative', 'Creative')], default='general', max_length=24),
        ),
        migrations.AlterField(
            model_name='driversource',
            name='key',
            field=models.SlugField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='driversource',
            unique_together={('key', 'customer_segment')},
        ),
    ]
